---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: dev
  labels:
    app: adservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: adservice-container
        image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/adservice:latest
        ports:
        - containerPort: 9555
          name: rpc
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_STATS
          value: "true"
        - name: DISABLE_TRACING
          value: "true"
        #- name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: dev
  labels:
    app: adservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc 
