---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: dev
  labels:
    app: checkoutservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: default
      containers:
        - name: checkoutservice-container
          image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/checkoutservice:latest
          ports:
          - containerPort: 5050
            name: rpc
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:80"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:80"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:80"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:80"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:80"
          - name: CART_SERVICE_ADDR
            value: "cartservice:80"

          - name: DISABLE_STATS
            value: "true"
          - name: DISABLE_TRACING
            value: "ture"
          - name: DISABLE_PROFILER
            value: "true"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: dev
  labels:
    app: checkoutservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc 