---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: currencyservice-container
        image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/currencyservice:latest
        ports:
        - name: rpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_TRACING
          value: "true"
        - name: DISABLE_PROFILER
          value: "true"
        - name: DISABLE_DEBUGGER
          value: "true"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc