---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: dev
  labels:
    app: emailservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: emailservice-container
        image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/emailservice:latest
        ports:
        - containerPort: 8080
          name: rpc
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "true"
        - name: DISABLE_PROFILER
          value: "true"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: dev
  labels:
    app: emailservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc