---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: dev
  labels:
    app: paymentservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: paymentservice-container
        image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/paymentservice:latest
        ports:
        - containerPort: 50051
          name: rpc
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: dev
  labels:
    app: paymentservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc 