---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: dev
  labels:
    app: recommendationservice
    project: telecom-project
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: recommendationservice-container
        image: 302990163096.dkr.ecr.eu-west-1.amazonaws.com/recommendationservice:latest
        ports:
        - containerPort: 8080
          name: rpc
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:80"
        - name: DISABLE_TRACING
          value: "true"
        - name: DISABLE_PROFILER
          value: "true"
        - name: DISABLE_DEBUGGER
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: dev
  labels:
    app: recommendationservice
    project: telecom-project
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: rpc
    port: 80
    targetPort: rpc 